print(10>9)
print(10==9)
print(10<9)
print(bool(False))
print(bool(None))
print(bool(0))
print(bool(""))
print(bool(()))
print(bool([]))
print(bool({}))
print(bool("abc"))
print(bool(123))
print(bool(["apple", "cherry", "banana"]))
